# Generated by Django 4.2.3 on 2023-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('image_content', models.URLField(blank=True)),
                ('image_content1', models.URLField(blank=True)),
                ('image_content2', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField()),
                ('telegram_publication_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('image_content', models.URLField(blank=True)),
                ('image_content1', models.URLField(blank=True)),
                ('image_content2', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField()),
                ('telegram_publication_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
