# Generated by Django 4.2.3 on 2023-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('image_content', models.URLField(blank=True)),
                ('image_content1', models.URLField(blank=True)),
                ('image_content2', models.URLField(blank=True)),
                ('age', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField()),
                ('telegram_publication_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
