# Generated by Django 4.2.3 on 2023-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshelter', '0002_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='image_content',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='image_content1',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='image_content2',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_content',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_content1',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_content2',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='image_content',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='image_content1',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='image_content2',
            field=models.ImageField(upload_to='petshelter/images'),
        ),
    ]
