# Generated by Django 4.2.3 on 2023-07-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshelter', '0003_alter_interactive_image_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_content',
            field=models.ImageField(blank=True, upload_to='petshelter/images'),
        ),
    ]
